apiVersion: batch/v1
kind: Job
metadata:
  name: job-{{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
      - name: job-{{ .Values.serviceName }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        {{- if .Values.volumeMounts }}
        volumeMounts:{{- include "zHelper.volumeMounts" . | nindent 12  }}
        {{- end }}
      imagePullSecrets:
      - name: dhub
      {{- if .Values.volumes }}
      volumes:
        {{- include "zHelper.volumes" . | nindent 8  }}
      {{- end }}
      restartPolicy: Never
  backoffLimit: 4